spring:
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: com.jl.bean
  mapper-locations: classpath:com/jl/dao/*.xml

---
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/ssm
    type: com.alibaba.druid.pool.DruidDataSource